# doc: https://skaffold.dev/docs/references/yaml
apiVersion: skaffold/v2beta19
kind: Config

profiles:
  - name: dev
    build:
      tagPolicy:
        gitCommit: {}
      artifacts:
        - image: helloworld-client
          docker:
            dockerfile: ./client/Dockerfile
        - image: helloworld-server
          docker:
            dockerfile: ./server/Dockerfile

deploy:
  kubectl:
    manifests:
      - "k8s/*.yaml"